version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_ROOT_NAME}
    volumes:
      - ./docker/mongo/mongodump:/mongodump
      - ./docker/mongo/data:/data/db
    ports:
      - "${MONGO_PORT_EXTERNAL}:27017"
    command: mongod --quiet --logpath /dev/null --logappend
    logging:
      driver: "none"
    env_file:
      - .env
